version: "3.8"
services:
  app:
    image: calculator-plus:${TAG:-latest}
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=9000
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - APP_HOST=app
      - APP_PORT=9000
    ports:
      - "9000:9000"
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome:latest
    environment:
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "4444:4444"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
